name: Release version

on:
  push:
    branches: [ main ]

jobs:
  release_version:
    name: Release version
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tag
        id: tagging
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tagging.outputs.new_tag }}
          token: ${{ secrets.PAT }}